CovidHealthcare/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CovidHealthcare.Models
{
    public class Hospital
    {
        public int Id { get; set; }
        public string HospitalName { get; set; }
        public string EmployeeName { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }

    }
}

CovidHealthcare/Controllers/DoctorsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CovidHealthcare.ControllerService;
using CovidHealthcare.ViewModel;

namespace CovidHealthcare.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DoctorsController : Controller
    {
        private readonly IDoctorControllerService controllerService;
        public DoctorsController(IDoctorControllerService controllerService)
        {
            this.controllerService = controllerService;
        }
        public ActionResult Index()
        {
            List<Doctor> Doctors = new List<Doctor>();
            Doctors = controllerService.GetDoctors();
            return View(Doctors);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Doctor Doctor)
        {
            if (ModelState.IsValid)
            {
                controllerService.CreateDoctor(Doctor);
                RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor Doctor = controllerService.GetDoctorById(id);
            if (Doctor == null)
            {
                return HttpNotFound();
            }
            return View(Doctor);
        }

        // POST: Doctors/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            controllerService.DeleteDoctorById(id);

            return RedirectToAction("Index");
        }


    }
}

CovidHealthcare/Controllers/HospitalsController.cs
using System.Web.Mvc;
using CovidHealthcare.ControllerService;
using CovidHealthcare.ViewModel;

namespace CovidHealthcare.Controllers
{
    public class HospitalsController : Controller
    {
        private readonly IHospitalControllerService hospitalControllerService;
        public HospitalsController(IHospitalControllerService hospitalControllerService)
        {
            this.hospitalControllerService = hospitalControllerService;
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                if (hospitalControllerService.IsInDatabase(hospital.Email))
                {
                    return Content("Email has been pre-registered");
                }
                hospitalControllerService.CreateHospital(hospital);
                return Content("Registration success!");
            }
            return View(hospital);
        }
    }
}

CovidHealthcare/Views/Admin/DeleteHospital.cshtml
@model  CovidHealthcare.ViewModel.Hospital

@{
    ViewBag.Title = "DeleteHospital";
}

<h2>Do you really want to Delete the below Hospital?</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hospital</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Hospitals")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CovidHealthcare/Views/Admin/Hospitals.cshtml
@model  IEnumerable<CovidHealthcare.ViewModel.Hospital>

@{
    ViewBag.Title = "Hospitals";
}

<h2>Hospitals</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HospitalName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HospitalName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>

                @Html.ActionLink("Add Request", "ApproveHospital", new { id = item.Id }) |
                @Html.ActionLink("Delete", "DeleteHospital", new { id = item.Id })
            </td>
        </tr>
    }

</table>

CovidHealthcare/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    <link href="~/Styles/buttons.css" rel="stylesheet" />

}
<ul id="buttons">
    <li>@Html.ActionLink("Registration", "Register", "Admin")</li>
    <li>@Html.ActionLink("Hospital ", "Hospitals", "Admin")</li>
    <li>@Html.ActionLink("Add New Doctor ", "Create", "Doctors")</li>
</ul>

CovidHealthcare/Views/Admin/Register.cshtml
@model  CovidHealthcare.ViewModel.RegisterViewModel

@{
    ViewBag.Title = "Register";
    <link href="~/Styles/LoginAndRegistration.css" rel="stylesheet" />
}


<div class="form">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Register</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserRoleId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.UserRoleId, new SelectList(Model.UserRole, "Id", "Role"), "--Select--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserRoleId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Login", "Login")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}